---

- hosts: dbservers
  user: vagrant
  sudo: True

  vars:
    neo4j_version: 1.9.4
    neo4j_download_url: http://dist.neo4j.org/neo4j-community-
    neo4j_download_suffix: -unix.tar.gz
    redis_version: 2.6.16
    redis_download_url: http://download.redis.io/releases/redis-
    redis_download_suffix: .tar.gz

  tasks:
    - name: update apt
      action: command /usr/bin/apt-get update

    - include: neo4j.yml
    - include: redis.yml
    - include: migrate-db.yml

  handlers:
    - name: Restart neo4j
      action: service name=neo4j-service state=restarted

    - name: Restart redis
      action: service name=redis_6379 state=restarted