---

- name: Install Java
  action: apt pkg=openjdk-7-jre-headless state=installed

- name: Install Curl
  action: apt pkg=curl state=installed

- name: Update /etc/security/limits.conf to raise open files count
  template: src=templates/etc_security_limits.conf dest=/etc/security/limits.conf owner=root group=root mode=0644

- name: Download Neo4j
  command: curl -O ${neo4j_download_url}${neo4j_version}${neo4j_download_suffix} chdir=/usr/lib creates=/usr/lib/neo4j-community-${neo4j_version}${neo4j_download_suffix}

- name: Unzip Neo4j
  command: tar -xzf /usr/lib/neo4j-community-${neo4j_version}${neo4j_download_suffix} chdir=/usr/lib creates=/usr/lib/neo4j-community-${neo4j_version}

- name: create neo4j user
  action: user name=neo4j

- name: mkdir /etc/neo4j-community-${neo4j_version}
  command: mkdir /etc/neo4j-community-${neo4j_version} creates=/etc/neo4j-community-${neo4j_version}

- name: Add Neo4j init script
  template: src=templates/neo4j.init dest=/etc/init.d/neo4j-service owner=root group=root mode=0777
  notify:
    - Restart neo4j