---

- name: Install Java
  action: >
    apt pkg=openjdk-7-jre-headless
    state=installed

- name: Install Curl
  action: >
    apt pkg=curl
    state=installed

- name: Download Neo4j
  command: >
    curl -O ${neo4j_download_url}${neo4j_version}${neo4j_download_suffix}
    chdir=/usr/lib
    creates=/usr/lib/neo4j-community-${neo4j_version}${neo4j_download_suffix}

- name: Unzip Neo4j
  command: >
    tar -xzf /usr/lib/neo4j-community-${neo4j_version}${neo4j_download_suffix}
    chdir=/usr/lib
    creates=/usr/lib/neo4j-community-${neo4j_version}

- name: create neo4j user
  action: user name=neo4j

- name: Update neo4j-wrapper.conf
  template: >
    src=templates/neo4j/neo4j-wrapper.conf
    dest=/usr/lib/neo4j-community-${neo4j_version}/conf/neo4j-wrapper.conf

- name: Update neo4j-server.properties
  template: >
    src=templates/neo4j/neo4j-server.properties
    dest=/usr/lib/neo4j-community-${neo4j_version}/conf/neo4j-server.properties

- name: Chown Neo4j lib
  command: chown -R neo4j:neo4j /usr/lib/neo4j-community-${neo4j_version}

- name: Add Neo4j init script
  template: >
    src=templates/neo4j/neo4j.init
    dest=/etc/init.d/neo4j-service
    owner=root
    group=root
    mode=0777

- name: Add Neo4j init to upstart
  command: update-rc.d neo4j-service defaults

- name: Restart Neo4j
  command: service neo4j-service restart