---

- name: Add vg.creo.prog conf (REMOTE)
  template: >
    src=templates/etc/nginx/sites-available/webvg-remote.conf
    dest=/etc/nginx-{{ nginx_version }}/sites-available/webvg-remote.conf
    owner={{ php_fpm_user }}
    group={{ php_fpm_group }}

- name: Symlink vg.creo.prog conf (REMOTE)
  file: >
    src=/etc/nginx-{{ nginx_version }}/sites-available/webvg-remote.conf
    dest=/etc/nginx-{{ nginx_version }}/sites-enabled/webvg-remote.conf
    owner={{ php_fpm_user }}
    group={{ php_fpm_group }}
    state=link

- name: Add remote.api.creo.prog conf (REMOTE)
  template: >
    src=templates/etc/nginx/sites-available/webapi-remote.conf
    dest=/etc/nginx-{{ nginx_version }}/sites-available/webapi-remote.conf
    owner={{ php_fpm_user }}
    group={{ php_fpm_group }}

- name: Symlink api.creo.prog conf (REMOTE)
  file: >
    src=/etc/nginx-{{ nginx_version }}/sites-available/webapi-remote.conf
    dest=/etc/nginx-{{ nginx_version }}/sites-enabled/webapi-remote.conf
    owner={{ php_fpm_user }}
    group={{ php_fpm_group }}
    state=link

- name: Add remote.scaffolding.creo.prog conf (REMOTE)
  template: >
    src=templates/etc/nginx/sites-available/webscaffolding-remote.conf
    dest=/etc/nginx-{{ nginx_version }}/sites-available/webscaffolding-remote.conf
    owner={{ php_fpm_user }}
    group={{ php_fpm_group }}

- name: Symlink scaffolding.creo.prog conf (REMOTE)
  file: >
    src=/etc/nginx-{{ nginx_version }}/sites-available/webscaffolding-remote.conf
    dest=/etc/nginx-{{ nginx_version }}/sites-enabled/webscaffolding-remote.conf
    owner={{ php_fpm_user }}
    group={{ php_fpm_group }}
    state=link

- name: Add remote API domain to hosts file
  lineinfile: >
    dest=/etc/hosts
    regexp=^{{ remote_api_domain }}
    line='127.0.0.1   {{ remote_api_domain }}'

- name: Symlink /vagrant/www/creo-api-application to /web/api.creo.prog
  file: >
    src=/vagrant/www/creo-api-application
    dest=/web/api.creo.prog
    owner={{ php_fpm_user }}
    group={{ php_fpm_group }}
    state=link

- name: Symlink /vagrant/www/videogamer-client-application to /web/vg.creo.prog
  file: >
    src=/vagrant/www/videogamer-client-application
    dest=/web/vg.creo.prog
    owner={{ php_fpm_user }}
    group={{ php_fpm_group }}
    state=link

- name: Symlink /vagrant/www/scaffolding to /web/scaffolding.creo.prog
  file: >
    src=/vagrant/www/scaffolding
    dest=/web/scaffolding.creo.prog
    owner={{ php_fpm_user }}
    group={{ php_fpm_group }}
    state=link

- name: Disable Opcache
  ini_file: >
    dest={{ php_ini_location }}/php.ini
    section=PHP
    option=opcache.enable
    value="Off"
    state=present

- name: Restart php5-fpm
  command: service php-{{ php_version }}-fpm restart

- name: Restart Nginx
  command: service nginx restart
