---

- name: Remove old Node
  command: rm -rf /usr/local/node

- name: test
  command: echo ${node_download_url}${node_download_suffix}

- name: Download Node
  command: curl -O ${node_download_url}${node_download_suffix} chdir=/usr/local creates=/usr/local/node-v${node_version}-linux-x64${node_download_suffix}

- name: Extract node
  command: tar -xzf /usr/local/node-v${node_version}-linux-x64${node_download_suffix}  chdir=/usr/local creates=/usr/local/node-v${node_version}-linux-x64

- name: Move into node/
  command: mv node-v${node_version}-linux-x64 node chdir=/usr/local

- name: Install Bower
  command: /usr/local/node/bin/npm install -g bower

- name: Install Grunt
  command: /usr/local/node/bin/npm install -g grunt

- name: Install grunt-cli
  command: /usr/local/node/bin/npm install -g grunt-cli