---

- name: Download Redis
  command: >
    curl -O ${redis_download_url}${redis_version}${redis_download_suffix}
    chdir=/usr/lib
    creates=/usr/lib/redis-${redis_version}${redis_download_suffix}

- name: Unzip Redis
  command: >
    tar -xzf /usr/lib/redis-${redis_version}${redis_download_suffix}
    chdir=/usr/lib
    creates=/usr/lib/redis-${redis_version}

- name: Make Redis
  command: >
    make chdir=/usr/lib/redis-${redis_version}
    creates=/usr/lib/redis-${redis_version}/src/redis-server

- name: mkdir /etc/redis
  command: >
    mkdir /etc/redis
    creates=/etc/redis

- name: mkdir -p /var/redis/6379
  command: >
    mkdir /var/redis
    creates=/var/redis

- name: Copy redis-server to bin
  command: >
    cp redis-server /usr/local/bin/
    chdir=/usr/lib/redis-${redis_version}/src
    creates=/usr/local/bin/redis-server

- name: Copy redis-cli to bin
  command: >
    cp redis-cli /usr/local/bin/
    chdir=/usr/lib/redis-${redis_version}/src
    creates=/usr/local/bin/redis-cli

- name: Add Redis init script
  template: >
    src=templates/redis/redis.init
    dest=/etc/init.d/redis_6379
    owner=root
    group=root
    mode=0777

- name: Add Redis init to upstart
  command: update-rc.d redis_6379 defaults

- name: Add Redis conf
  template: >
    src=templates/redis/redis.conf
    dest=/etc/redis/6379.conf

- name: Stop Redis
  command: service redis_6379 stop

- name: Start Redis
  command: service redis_6379 start