---

- hosts: staging_webservers
  remote_user: ansible
  sudo: true

  vars:
    new_folder: "staging-api-pro-gmedia.com-{{ lookup('pipe','date +%Y%m%d-%H%M') }}"
    tarball_file: staging-api-pro-gmedia-com.tar.gz
    symlink_file: staging-api-pro-gmedia.com-latest

  tasks:
    - name: Copy the staging-api-pro-gmedia-com.tar.gz to the webserver
      copy: >
        src=/home/developer/staging-files/${tarball_file}
        dest=/web/${tarball_file}

    - name: Stop nginx
      command: service nginx stop

    - name: Remove the old symlink if it exists
      command: >
        rm -f ${symlink_file}
        chdir=/web

    - name: mkdir new_folder
      command: >
        mkdir ${new_folder}
        chdir=/web

    - name: Unzip into new_folder
      command: >
        tar xzf ${tarball_file} -C ${new_folder}
        chdir=/web

    - name: Symlink symlink_file to new_folder
      file: >
        src=${new_folder}
        dest=${symlink_file}
        owner=${php_fpm_user}
        group=${php_fpm_group}
        state=link
        chdir=/web

    - name: Restart nginx
      command: service nginx start