---

- hosts: staging_webservers
  remote_user: ansible
  sudo: true

  vars:
    new_folder: staging-videogamer-com
    tarball_file: staging-videogamer-com.tar.gz
    php_fpm_user: www-data
    php_fpm_group: www-data

  tasks:

    - name: Chmod the folder so we can write to it
      command: >
        chmod -R 777 /web/{{ new_folder }}

    - name: Chown the folder so we can write to it
      command: >
        chown -R ansible:ansible /web/{{ new_folder }}

    - name: Rsync the folder
      synchronize: >
        src=/var/lib/jenkins/workspace/deploy-staging.videogamer.com/videogamer-client-application-temp
        dest=/web/{{ new_folder }}
        recursive=yes
        delete=yes
        times=no
        owner=no
        group=no

    - name: Change ownership of web dir
      command: >
        chown -R {{ php_fpm_user }}:{{ php_fpm_group }} {{ new_folder }}
        chdir=/web

    - name: Flush the PHP opcache
      command: curl http://{{ api_domain }}/cache_buster.php
