---

- hosts: staging_webservers
  remote_user: ansible
  sudo: true

  vars:
    new_folder: staging-api-pro-gmedia-com
    tarball_file: staging-api-pro-gmedia-com.tar.gz
    php_fpm_user: www-data
    php_fpm_group: www-data

  tasks:

    - name: Chmod the folder so we can write to it
      command: >
        chmod -R 777 /web/{{ new_folder }}

    - name: Rsync the folder
      synchronize: >
        src=/var/lib/jenkins/workspace/deploy-staging.api.pro-gmedia.com/api-application-temp
        dest=/web/{{ new_folder }}
        recursive=yes
        delete=yes


    - name: Change ownership of web dir
      command: >
        chown -R {{ php_fpm_user }}:{{ php_fpm_group }} {{ new_folder }}
        chdir=/web

    - name: Flush the PHP opcache
      command: curl http://{{ api_domain }}/cache_buster.php
