---

- hosts: staging_webservers
  remote_user: ansible
  sudo: true

  vars:
    new_folder: staging-api-pro-gmedia-com
    tarball_file: staging-api-pro-gmedia-com.tar.gz
    php_fpm_user: www-data
    php_fpm_group: www-data

  tasks:

    - name: Rsync the folder
      copy: >
        src=/var/lib/jenkins/workspace/deploy-staging.api.pro-gmedia.com/{{ new_folder }}
        dest=/web/{{ new_folder }}

    - name: Change ownership of web dir
      command: >
        chown -R {{ php_fpm_user }}:{{ php_fpm_group }} {{ new_folder }}
        chdir=/web

    - name: Flush the PHP opcache
      command: curl http://{{ api_domain }}/cache_buster.php
