---

- hosts: dev_dbservers
  user: vagrant
  sudo: True

  vars:
    neo4j_version: 1.9.4
    neo4j_download_url: http://dist.neo4j.org/neo4j-community-
    neo4j_download_suffix: -unix.tar.gz
    redis_version: 2.6.16
    redis_download_url: http://download.redis.io/releases/redis-
    redis_download_suffix: .tar.gz
    elastic_version: 1.1.1
    elastic_download_url: https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-
    elastic_download_suffix: .deb

  tasks:
    - name: update apt
      action: command /usr/bin/apt-get update

    #- include: includes/neo4j.yml
    - include: includes/redis.yml
    - include: includes/elastic.yml

    - name: Set .bashrc
      action: copy src=files/.bashrc-db dest=/home/vagrant/.bashrc owner=vagrant group=vagrant

  handlers:
    - name: Restart neo4j
      action: service name=neo4j-service state=restarted

    - name: Restart redis
      action: service name=redis_6379 state=restarted