---

- hosts: staging_redisservers
  user: developer
  sudo: True

  vars:
    redis_version: 2.6.16
    redis_download_url: http://download.redis.io/releases/redis-
    redis_download_suffix: .tar.gz

  tasks:
    - name: update apt
      action: command /usr/bin/apt-get update

    - include: includes/redis.yml
    - include: includes/newrelic.yml

    - name: Set .bashrc
      action: copy src=files/.bashrc-db dest=/home/developer/.bashrc owner=developer group=developer

    - name: Clear old firewall rules
      action: command /usr/sbin/ufw disable && /usr/sbin/ufw --force reset

    - name: Set new default rules
      action: command /usr/sbin/ufw $item
      with_items:
        - default deny incoming
        - default allow outgoing
        - allow ssh
        - allow ntp

    - name: Allow webservers access
      action: command /usr/sbin/ufw allow proto tcp from $item to any port 6379
      with_items:
        - ${groups.staging_webservers}
        - 82.136.1.154

  handlers:
    - name: Restart redis
      action: service name=redis_6379 state=restarted