---

- hosts: staging_neo4jservers
  user: developer
  sudo: True

  vars:
    neo4j_version: 1.9.4
    neo4j_download_url: http://dist.neo4j.org/neo4j-community-
    neo4j_download_suffix: -unix.tar.gz

  tasks:
    - name: update apt
      action: command /usr/bin/apt-get update

    - include: includes/neo4j.yml

    - name: Set .bashrc
      action: copy src=files/.bashrc-db dest=/home/developer/.bashrc owner=developer group=developer

    - name: Clear old firewall rules
      action: command /usr/sbin/ufw disable && /usr/sbin/ufw --force reset

    - name: Set new default rules
      action: command /usr/sbin/ufw $item
      with_items:
        - default deny incoming
        - default deny outgoing
        - allow ssh
        - allow ntp

    - name: Allow webservers access
      action: command /usr/sbin/ufw allow proto tcp from $item to any port 7474
      with_items:
        - ${groups.staging_webservers}

    - name: Enable firewall rules
      action: command /usr/sbin/ufw --force enable

  handlers:
    - name: Restart neo4j
      action: service name=neo4j-service state=restarted